import {
  emptyEmbed,
  type AppState,
  type AuditEntry,
  type DiscordEmbed,
  type Post,
} from "./types";

/** Day-granularity anchor so server and client seeds match. */
function anchor(): Date {
  const n = new Date();
  return new Date(Date.UTC(n.getUTCFullYear(), n.getUTCMonth(), n.getUTCDate(), 12, 0, 0));
}

function day(offset: number, hour = 17, minute = 0): string {
  const a = anchor();
  a.setUTCDate(a.getUTCDate() + offset);
  a.setUTCHours(hour, minute, 0, 0);
  return a.toISOString();
}

function embed(partial: Partial<DiscordEmbed>): DiscordEmbed {
  return { ...emptyEmbed(), ...partial };
}

const avatar = (seed: string) =>
  `https://api.dicebear.com/9.x/bottts-neutral/svg?seed=${seed}&backgroundColor=5865f2`;
const person = (seed: string) =>
  `https://api.dicebear.com/9.x/notionists/svg?seed=${seed}&backgroundColor=b6e3f4`;

export function buildSeed(): AppState {
  const organizations = [
    { id: "org-nova", name: "Nova Esports", tag: "Gaming / Esports Org", accent: "#5865F2", plan: "Scale" },
    { id: "org-hub", name: "Community Hub", tag: "Creator Community", accent: "#EB459E", plan: "Growth" },
  ];

  const members = [
    {
      id: "u-riya",
      orgIds: ["org-nova", "org-hub"],
      name: "Riya Kapoor",
      handle: "riya",
      role: "super_admin" as const,
      avatar: person("riya"),
      email: "riya@novaesports.gg",
    },
    {
      id: "u-marcus",
      orgIds: ["org-nova"],
      name: "Marcus Webb",
      handle: "marcus",
      role: "admin" as const,
      avatar: person("marcus"),
      email: "marcus@novaesports.gg",
    },
    {
      id: "u-sana",
      orgIds: ["org-nova", "org-hub"],
      name: "Sana Ali",
      handle: "sana",
      role: "approver" as const,
      avatar: person("sana"),
      email: "sana@novaesports.gg",
    },
    {
      id: "u-dev",
      orgIds: ["org-nova"],
      name: "Devon Pierce",
      handle: "devon",
      role: "user" as const,
      avatar: person("devon"),
      email: "devon@novaesports.gg",
    },
    {
      id: "u-lena",
      orgIds: ["org-hub"],
      name: "Lena Ortiz",
      handle: "lena",
      role: "user" as const,
      avatar: person("lena"),
      email: "lena@communityhub.io",
    },
  ];

  const servers = [
    {
      id: "srv-nova-main",
      orgId: "org-nova",
      name: "Nova Esports HQ",
      icon: avatar("nova"),
      botName: "Nova Herald",
      botAvatar: avatar("herald"),
      connection: "bot_token" as const,
      credential: "MTA5•••••••••••••••••••••••XyZ",
      connected: true,
      memberCount: 48210,
    },
    {
      id: "srv-nova-comp",
      orgId: "org-nova",
      name: "Nova Competitive",
      icon: avatar("comp"),
      botName: "Nova Referee",
      botAvatar: avatar("referee"),
      connection: "webhook" as const,
      credential: "https://discord.com/api/webhooks/•••/•••",
      connected: true,
      memberCount: 9120,
    },
    {
      id: "srv-hub-main",
      orgId: "org-hub",
      name: "Community Hub",
      icon: avatar("hub"),
      botName: "Hub Bulletin",
      botAvatar: avatar("bulletin"),
      connection: "bot_token" as const,
      credential: "MTE2•••••••••••••••••••••••QwE",
      connected: true,
      memberCount: 15780,
    },
    {
      id: "srv-hub-creators",
      orgId: "org-hub",
      name: "Creator Lounge",
      icon: avatar("lounge"),
      botName: "Hub Bulletin",
      botAvatar: avatar("bulletin"),
      connection: "bot_token" as const,
      credential: "",
      connected: false,
      memberCount: 2340,
    },
  ];

  const channels = [
    { id: "ch-announcements", serverId: "srv-nova-main", name: "announcements", type: "announcement" as const, requiresApproval: true },
    { id: "ch-tournaments", serverId: "srv-nova-main", name: "tournaments", type: "announcement" as const, requiresApproval: true },
    { id: "ch-giveaways", serverId: "srv-nova-main", name: "giveaways", type: "text" as const, requiresApproval: true },
    { id: "ch-general", serverId: "srv-nova-main", name: "general", type: "text" as const, requiresApproval: false },
    { id: "ch-scrims", serverId: "srv-nova-comp", name: "scrim-signups", type: "text" as const, requiresApproval: false },
    { id: "ch-patch", serverId: "srv-nova-comp", name: "patch-notes", type: "announcement" as const, requiresApproval: true },
    { id: "ch-hub-news", serverId: "srv-hub-main", name: "hub-news", type: "announcement" as const, requiresApproval: true },
    { id: "ch-hub-events", serverId: "srv-hub-main", name: "events", type: "text" as const, requiresApproval: true },
    { id: "ch-hub-chat", serverId: "srv-hub-main", name: "lounge-chat", type: "text" as const, requiresApproval: false },
    { id: "ch-creator-drops", serverId: "srv-hub-creators", name: "creator-drops", type: "text" as const, requiresApproval: false },
  ];

  const base = {
    buttons: [],
    attachments: [] as string[],
    timezone: "UTC",
    publishedAt: null,
    deliveryNote: null,
    revision: 1,
  };

  const posts: Post[] = [
    {
      ...base,
      id: "p-1",
      orgId: "org-nova",
      serverId: "srv-nova-main",
      channelId: "ch-tournaments",
      authorId: "u-dev",
      title: "Nova Open Season 7 — Registration",
      kind: "embed",
      content: "@everyone Registration is live!",
      embed: embed({
        authorName: "Nova Esports",
        authorIcon: avatar("nova"),
        title: "Nova Open — Season 7",
        titleUrl: "https://novaesports.gg/open",
        description:
          "**$25,000 prize pool.** 128 teams, double elimination, open to all regions.\n\nRegistration closes Friday 23:59 UTC. Read the [rulebook](https://novaesports.gg/rules) before signing up.",
        color: "#5865F2",
        thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=256&q=70",
        image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=70",
        fields: [
          { id: "f1", name: "Format", value: "Double Elim · BO3", inline: true },
          { id: "f2", name: "Region", value: "Global", inline: true },
          { id: "f3", name: "Entry", value: "Free", inline: true },
          { id: "f4", name: "Schedule", value: "Group stage Sat · Playoffs Sun", inline: false },
        ],
        footerText: "Nova Competitive Division",
        footerIcon: avatar("comp"),
      }),
      buttons: [
        { id: "b1", label: "Register team", url: "https://novaesports.gg/register", style: "link" },
        { id: "b2", label: "Rulebook", url: "https://novaesports.gg/rules", style: "link" },
      ],
      status: "pending",
      scheduledAt: day(2, 16),
      createdAt: day(-3, 9),
      updatedAt: day(-1, 11),
    },
    {
      ...base,
      id: "p-2",
      orgId: "org-nova",
      serverId: "srv-nova-main",
      channelId: "ch-giveaways",
      authorId: "u-dev",
      title: "Jersey drop giveaway",
      kind: "embed",
      content: "",
      embed: embed({
        title: "🎁 Season 7 Jersey Giveaway",
        description:
          "Three signed jerseys up for grabs. React with 🎉 to enter.\n\n*Winners announced live on stream.*",
        color: "#EB459E",
        fields: [
          { id: "f1", name: "Prizes", value: "3× signed jersey", inline: true },
          { id: "f2", name: "Ends", value: "In 48 hours", inline: true },
        ],
        footerText: "One entry per member",
      }),
      status: "changes_requested",
      scheduledAt: null,
      createdAt: day(-4, 14),
      updatedAt: day(-1, 15),
      revision: 2,
    },
    {
      ...base,
      id: "p-3",
      orgId: "org-nova",
      serverId: "srv-nova-comp",
      channelId: "ch-patch",
      authorId: "u-marcus",
      title: "Patch 7.4 competitive ruleset",
      kind: "embed",
      content: "",
      embed: embed({
        title: "Patch 7.4 — Competitive Ruleset",
        description:
          "The following changes take effect for all official matches starting Monday.",
        color: "#1ABC9C",
        fields: [
          { id: "f1", name: "Map pool", value: "Added Dockside, removed Foundry", inline: false },
          { id: "f2", name: "Bans", value: "Two bans per side", inline: true },
          { id: "f3", name: "Pause limit", value: "3 × 90s", inline: true },
        ],
        footerText: "Nova Rules Committee",
      }),
      status: "scheduled",
      scheduledAt: day(1, 15, 30),
      createdAt: day(-6, 10),
      updatedAt: day(-2, 10),
    },
    {
      ...base,
      id: "p-4",
      orgId: "org-nova",
      serverId: "srv-nova-main",
      channelId: "ch-announcements",
      authorId: "u-marcus",
      title: "Roster announcement — Valorant division",
      kind: "embed",
      content: "@here Big news 👇",
      embed: embed({
        authorName: "Nova Esports",
        authorIcon: avatar("nova"),
        title: "Welcome to Nova, Kestrel!",
        description:
          "Our Valorant roster is complete. **Kestrel** joins as flex support ahead of Season 7.",
        color: "#57F287",
        image: "https://images.unsplash.com/photo-1587573089734-599851b0c5cf?w=1200&q=70",
        footerText: "Nova Esports",
      }),
      status: "published",
      scheduledAt: day(-5, 18),
      publishedAt: day(-5, 18),
      deliveryNote: "Delivered to #announcements · 1 message, 1 embed · 3.2k reactions",
      createdAt: day(-8, 12),
      updatedAt: day(-5, 18),
    },
    {
      ...base,
      id: "p-5",
      orgId: "org-nova",
      serverId: "srv-nova-main",
      channelId: "ch-general",
      authorId: "u-dev",
      title: "Weekly community night reminder",
      kind: "message",
      content:
        "**Community Night is tonight at 20:00 UTC** 🎮\nJump into <#ch-general> voice for casual customs — everyone welcome!",
      embed: emptyEmbed(),
      status: "draft",
      scheduledAt: null,
      createdAt: day(-1, 8),
      updatedAt: day(-1, 8),
    },
    {
      ...base,
      id: "p-6",
      orgId: "org-nova",
      serverId: "srv-nova-main",
      channelId: "ch-announcements",
      authorId: "u-dev",
      title: "Merch restock teaser",
      kind: "embed",
      content: "",
      embed: embed({
        title: "Merch restock incoming",
        description: "Hoodies and mousepads are back next week.",
        color: "#FEE75C",
        footerText: "Nova Store",
      }),
      status: "rejected",
      scheduledAt: null,
      createdAt: day(-7, 9),
      updatedAt: day(-6, 16),
    },
    {
      ...base,
      id: "p-7",
      orgId: "org-nova",
      serverId: "srv-nova-comp",
      channelId: "ch-scrims",
      authorId: "u-marcus",
      title: "Scrim block signups",
      kind: "message",
      content: "Scrim blocks for this week are open. Drop your team tag and preferred slot below.",
      embed: emptyEmbed(),
      status: "failed",
      scheduledAt: day(-2, 13),
      deliveryNote: "Discord API error 50013 — bot missing Send Messages in #scrim-signups",
      createdAt: day(-3, 13),
      updatedAt: day(-2, 13),
    },
    {
      ...base,
      id: "p-8",
      orgId: "org-hub",
      serverId: "srv-hub-main",
      channelId: "ch-hub-news",
      authorId: "u-lena",
      title: "Creator AMA with Mira",
      kind: "embed",
      content: "@everyone",
      embed: embed({
        authorName: "Community Hub",
        authorIcon: avatar("hub"),
        title: "Community AMA — Mira Chen",
        description:
          "Bring your questions about growing a channel from zero. Live in the stage channel.",
        color: "#9B59B6",
        fields: [
          { id: "f1", name: "When", value: "Thursday 18:00 UTC", inline: true },
          { id: "f2", name: "Where", value: "Stage · Main Hall", inline: true },
        ],
        footerText: "Community Hub Events",
      }),
      buttons: [{ id: "b1", label: "Add to calendar", url: "https://communityhub.io/ama", style: "link" }],
      status: "pending",
      scheduledAt: day(3, 18),
      createdAt: day(-2, 11),
      updatedAt: day(-1, 9),
    },
    {
      ...base,
      id: "p-9",
      orgId: "org-hub",
      serverId: "srv-hub-main",
      channelId: "ch-hub-events",
      authorId: "u-lena",
      title: "Event reminder — Portfolio review",
      kind: "embed",
      content: "",
      embed: embed({
        title: "⏰ Portfolio Review starts in 1 hour",
        description: "Hop in early to claim a review slot — first 20 people only.",
        color: "#ED4245",
        footerText: "Community Hub",
      }),
      status: "approved",
      scheduledAt: day(4, 17),
      createdAt: day(-2, 15),
      updatedAt: day(-1, 12),
    },
    {
      ...base,
      id: "p-10",
      orgId: "org-hub",
      serverId: "srv-hub-main",
      channelId: "ch-hub-chat",
      authorId: "u-lena",
      title: "Weekly roundup",
      kind: "message",
      content: "Here's what happened this week in the Hub — 12 new creators, 4 collabs, 1 very cursed meme.",
      embed: emptyEmbed(),
      status: "published",
      scheduledAt: day(-6, 12),
      publishedAt: day(-6, 12),
      deliveryNote: "Delivered to #lounge-chat · 1 message",
      createdAt: day(-7, 12),
      updatedAt: day(-6, 12),
    },
    {
      ...base,
      id: "p-11",
      orgId: "org-nova",
      serverId: "srv-nova-main",
      channelId: "ch-tournaments",
      authorId: "u-marcus",
      title: "Season 7 bracket reveal",
      kind: "embed",
      content: "",
      embed: embed({
        title: "Season 7 Bracket Reveal",
        description: "All 128 teams seeded. Check your path to the finals.",
        color: "#5865F2",
        footerText: "Nova Open",
      }),
      status: "scheduled",
      scheduledAt: day(6, 19),
      createdAt: day(-1, 16),
      updatedAt: day(-1, 16),
    },
    {
      ...base,
      id: "p-12",
      orgId: "org-nova",
      serverId: "srv-nova-main",
      channelId: "ch-giveaways",
      authorId: "u-dev",
      title: "Old sticker giveaway (cancelled)",
      kind: "message",
      content: "Sticker pack giveaway — cancelled, stock went to the tournament prize pool instead.",
      embed: emptyEmbed(),
      status: "cancelled",
      scheduledAt: null,
      createdAt: day(-10, 10),
      updatedAt: day(-9, 10),
    },
  ];

  const audit: AuditEntry[] = [
    { id: "a1", postId: "p-1", actorId: "u-dev", action: "created", at: day(-3, 9) },
    { id: "a2", postId: "p-1", actorId: "u-dev", action: "submitted", note: "Ready for review — copy approved by comms.", at: day(-3, 10) },
    { id: "a3", postId: "p-1", actorId: "u-sana", action: "comment", note: "Checking prize pool number with finance before approving.", at: day(-1, 11) },
    { id: "a4", postId: "p-2", actorId: "u-dev", action: "created", at: day(-4, 14) },
    { id: "a5", postId: "p-2", actorId: "u-dev", action: "submitted", at: day(-4, 15) },
    { id: "a6", postId: "p-2", actorId: "u-sana", action: "changes_requested", note: "Add the entry deadline in UTC and mention the shipping regions.", at: day(-1, 15) },
    { id: "a7", postId: "p-3", actorId: "u-marcus", action: "created", at: day(-6, 10) },
    { id: "a8", postId: "p-3", actorId: "u-sana", action: "approved", note: "Ruleset matches committee minutes.", at: day(-2, 9) },
    { id: "a9", postId: "p-3", actorId: "u-marcus", action: "scheduled", note: "Scheduled for tomorrow 15:30 UTC", at: day(-2, 10) },
    { id: "a10", postId: "p-4", actorId: "u-marcus", action: "created", at: day(-8, 12) },
    { id: "a11", postId: "p-4", actorId: "u-riya", action: "approved", note: "Great — push it.", at: day(-6, 9) },
    { id: "a12", postId: "p-4", actorId: "u-marcus", action: "published", note: "Delivered to #announcements", at: day(-5, 18) },
    { id: "a13", postId: "p-6", actorId: "u-dev", action: "submitted", at: day(-7, 10) },
    { id: "a14", postId: "p-6", actorId: "u-sana", action: "rejected", note: "Store date isn't locked yet — resubmit when logistics confirm.", at: day(-6, 16) },
    { id: "a15", postId: "p-7", actorId: "u-marcus", action: "failed", note: "Discord API error 50013 — missing permissions", at: day(-2, 13) },
    { id: "a16", postId: "p-8", actorId: "u-lena", action: "created", at: day(-2, 11) },
    { id: "a17", postId: "p-8", actorId: "u-lena", action: "submitted", note: "Guest confirmed for Thursday.", at: day(-1, 9) },
    { id: "a18", postId: "p-9", actorId: "u-sana", action: "approved", note: "Approved, schedule it for Friday.", at: day(-1, 12) },
    { id: "a19", postId: "p-10", actorId: "u-lena", action: "published", note: "Delivered to #lounge-chat", at: day(-6, 12) },
    { id: "a20", postId: "p-12", actorId: "u-riya", action: "cancelled", note: "Stock reallocated.", at: day(-9, 10) },
  ];

  const templates = [
    {
      id: "t-1",
      orgId: "org-nova",
      name: "Tournament Announcement",
      category: "Tournaments",
      description: "Prize pool, format and registration CTA with bracket link.",
      kind: "embed" as const,
      content: "@everyone",
      embed: embed({
        authorName: "Nova Esports",
        authorIcon: avatar("nova"),
        title: "{{TOURNAMENT NAME}}",
        description: "**{{PRIZE POOL}} prize pool.** {{TEAM COUNT}} teams, {{FORMAT}}.\n\nRegistration closes {{DEADLINE}}.",
        color: "#5865F2",
        fields: [
          { id: "f1", name: "Format", value: "{{FORMAT}}", inline: true },
          { id: "f2", name: "Region", value: "{{REGION}}", inline: true },
          { id: "f3", name: "Entry", value: "Free", inline: true },
        ],
        footerText: "Nova Competitive Division",
      }),
      buttons: [{ id: "b1", label: "Register team", url: "https://novaesports.gg/register", style: "link" as const }],
      uses: 34,
    },
    {
      id: "t-2",
      orgId: "org-nova",
      name: "Giveaway",
      category: "Community",
      description: "Prize list, entry mechanic, deadline and winner rules.",
      kind: "embed" as const,
      content: "",
      embed: embed({
        title: "🎁 {{PRIZE}} Giveaway",
        description: "React with 🎉 to enter.\n\n*Winners drawn {{DRAW DATE}} — one entry per member.*",
        color: "#EB459E",
        fields: [
          { id: "f1", name: "Prizes", value: "{{PRIZES}}", inline: true },
          { id: "f2", name: "Ends", value: "{{DEADLINE}}", inline: true },
        ],
        footerText: "Shipping: {{REGIONS}}",
      }),
      buttons: [],
      uses: 21,
    },
    {
      id: "t-3",
      orgId: "org-nova",
      name: "Patch Update",
      category: "Product",
      description: "Structured changelog fields for balance and map changes.",
      kind: "embed" as const,
      content: "",
      embed: embed({
        title: "Patch {{VERSION}} — Highlights",
        description: "Live for all official matches from {{DATE}}.",
        color: "#1ABC9C",
        fields: [
          { id: "f1", name: "Balance", value: "{{CHANGES}}", inline: false },
          { id: "f2", name: "Maps", value: "{{MAPS}}", inline: true },
          { id: "f3", name: "Bug fixes", value: "{{FIXES}}", inline: true },
        ],
        footerText: "Nova Rules Committee",
      }),
      buttons: [{ id: "b1", label: "Full patch notes", url: "https://novaesports.gg/patch", style: "link" as const }],
      uses: 12,
    },
    {
      id: "t-4",
      orgId: "org-hub",
      name: "Event Reminder",
      category: "Events",
      description: "Short urgent reminder with time, place and slot cap.",
      kind: "embed" as const,
      content: "",
      embed: embed({
        title: "⏰ {{EVENT}} starts in {{TIME}}",
        description: "{{DETAILS}}",
        color: "#ED4245",
        fields: [
          { id: "f1", name: "When", value: "{{WHEN}}", inline: true },
          { id: "f2", name: "Where", value: "{{WHERE}}", inline: true },
        ],
        footerText: "Community Hub Events",
      }),
      buttons: [],
      uses: 47,
    },
    {
      id: "t-5",
      orgId: "org-hub",
      name: "Community AMA",
      category: "Events",
      description: "Guest intro, topic list and question submission link.",
      kind: "embed" as const,
      content: "@everyone",
      embed: embed({
        authorName: "Community Hub",
        authorIcon: avatar("hub"),
        title: "Community AMA — {{GUEST}}",
        description: "{{BIO}}\n\nDrop questions in the thread ahead of time.",
        color: "#9B59B6",
        fields: [
          { id: "f1", name: "When", value: "{{WHEN}}", inline: true },
          { id: "f2", name: "Where", value: "Stage · Main Hall", inline: true },
        ],
        footerText: "Community Hub Events",
      }),
      buttons: [{ id: "b1", label: "Submit a question", url: "https://communityhub.io/ama", style: "link" as const }],
      uses: 9,
    },
  ];

  const media = [
    { id: "m-1", orgId: "org-nova", name: "Season 7 hero banner", url: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=70", kind: "banner" as const, tags: ["tournament", "season7"], addedAt: day(-20, 10) },
    { id: "m-2", orgId: "org-nova", name: "Nova crest thumbnail", url: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&q=70", kind: "thumbnail" as const, tags: ["brand"], addedAt: day(-40, 10) },
    { id: "m-3", orgId: "org-nova", name: "Roster reveal art", url: "https://images.unsplash.com/photo-1587573089734-599851b0c5cf?w=1200&q=70", kind: "banner" as const, tags: ["roster", "valorant"], addedAt: day(-12, 10) },
    { id: "m-4", orgId: "org-nova", name: "Giveaway confetti", url: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=1200&q=70", kind: "banner" as const, tags: ["giveaway"], addedAt: day(-9, 10) },
    { id: "m-5", orgId: "org-hub", name: "Hub events banner", url: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1200&q=70", kind: "banner" as const, tags: ["events"], addedAt: day(-15, 10) },
    { id: "m-6", orgId: "org-hub", name: "AMA stage backdrop", url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=70", kind: "banner" as const, tags: ["ama", "stage"], addedAt: day(-5, 10) },
    { id: "m-7", orgId: "org-hub", name: "Hub mark", url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&q=70", kind: "icon" as const, tags: ["brand"], addedAt: day(-30, 10) },
  ];

  return {
    organizations,
    members,
    servers,
    channels,
    posts,
    templates,
    media,
    audit,
    currentOrgId: "org-nova",
    currentUserId: "u-riya",
  };
}
